// <auto-generated />
namespace FitnessTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addworkouts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addworkouts));
        
        string IMigrationMetadata.Id
        {
            get { return "202012181614589_add-workouts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
